var _vaq=_vaq||[];_vaq.push(['_setDomainName','jinfuzi.com']);_vaq.push(['_setAutoOutbound',true]);_vaq.push(['_setAutoTrackForm',true]);(function(r,F,Da){function G(a,c){null!=a||(a="yyyy-MM-dd HH:mm:ss");var b=c||new Date,d=b.getMonth()+1,g=b.getDate(),f=b.getHours(),l=b.getMinutes(),h=b.getSeconds(),e=function(a){return 10<=a?a+"":"0"+a},b=a[w]("yyyy",b.getFullYear()),b=b[w]("MM",e(d)),b=b[w]("dd",e(g)),b=b[w]("HH",e(f)),b=b[w]("mm",e(l));return b=b[w]("ss",e(h))}function ga(a,c,b){a.addEventListener?a.addEventListener(c,b,!1):a.attachEvent&&a.attachEvent("on"+c,b)}function Z(a,c,b){if((a=N(a))&&c&&b)if(aa[c])aa[c][u]({selector:a,
handler:b});else aa[c]=[{selector:a,handler:b}],ga(F,c,function(a){a=a||window.event;var b=a.target||a.srcElement,f=aa[c];if(f)for(var l=0,h=f[m];l<h;l++){var e=na(b,f[l].selector);e&&f[l].handler&&f[l].handler.call(e,a)}})}function na(a,c){if(!a||!c)return null;for(var b=c[x](" "),d=[],g=0,f=b.length;g<f;g++)b[g]&&d.push(b[g]);if(!oa(a,d.pop()))return a.ownerDocument&&(a=a.parentNode)?na(a,c):null;for(b=a;a&&a.ownerDocument&&(a=a.parentNode);)if(oa(a,d[d[m]-1])&&d.pop(),!d[m])return b;return null}
function oa(a,c){var b=/^(\w+)?(?:(\.|#)(\w+))?/.exec(N(c));if(!b||b[1]&&a.nodeName[I]()!=b[1][I]())return!1;var d=!0;switch(b[2]){case "#":d=a.id&&a.id==b[3];break;case ".":d=a.className&&RegExp("(^|\\s)"+b[3]+"(\\s|$)").test(a.className)}return d}function ha(a){var c=0,b=0,d;for(d=a[m]-1;0<=d;d--)b=a.charCodeAt(d),c=(c<<6&268435455)+b+(b<<14),b=c&266338304,c=0!=b?c^b>>21:c;return c}function pa(){for(var a=T.round(4294967295*T.random()).toString(16),c=a[m];8>c;c++)a="0"+a;return a[I]()}function L(a){return(a?
a[qa]:F[qa])||""}function ba(a){var c;a:{var b;b=ca+a;c=[];var d=F.cookie[x](";"),g=RegExp("^\\s*"+b+"=\\s*(.*?)\\s*$");for(b=0;b<d[m];b++){var f=d[b].match(g);f&&c[u](f[1])}d=ha(U)+".";for(b=0;b<c[m];b++)if(0==c[b][A](d)){c=c[b][x](d)[1];break a}c=""}if(!c)a:{try{b:{var l=r.localStorage.getItem(ca+a),h,e;if(l&&(h=l[A]("|"),e=l[s](0,h),-1!=h&&e>(new Date)[O]())){c=l[s](h+1);break b}c=""}break a}catch(p){}c=""}a=c;return null===a?"":a}function ia(a,c,b,d){var g=new Date;g.setTime(g[O]()+1E3*d);F.cookie=
ca+a+"="+ha(U)+"."+c+"; expires="+g.toUTCString()+"; path=/; domain="+b+";";try{r.localStorage.setItem(ca+a,g[O]()+"|"+c)}catch(f){}}function R(a,c,b){if("object"!=typeof a)return 0;a.ts=T.round((new Date)[O]()/1E3);c=c||ra+"?"+sa(a);b=b||Ea;var d=new Image(1,1);d.src=c;d.onload=function(){d.onload=null;d.onerror=null;b()};d.onerror=function(){d.onload=null;d.onerror=null;b()};return 1}function M(a){a.vData=ta();var c=ba("v"),b=c?c[x]("|"):[],d=c?b[3][x]("."):[],g;g=b[4]?b[4]:0;var f;if(!da){f=L();
var l=V(f),h=l.host[I](),e;e="utm_source utm_medium utm_campaign utm_content utm_term utm_from utm_group utm_creative utm_keyword utm_network utm_placement".split(" ");var n=V(r[P].href),k=L(),k=k?V(k):{},n=ua(n.query+"&"+n.hash[w]("?","&")),q=[],t,y,v,s=["hmsr","hmmd","hmpl","hmci","hmkw"];t=0;for(y=s[m];t<y;t++)n[s[t]]&&(n[e[t]]=n[s[t]]);r._e360_creativeid?(n[e[0]]="360",n[e[1]]="cpc",n[e[7]]=r._e360_creativeid,n[e[8]]=r._e360_keywordid):n[e[0]]||!(v="cpro.baidu.com"==k.host)&&!n.bdclkid?n[e[0]]||
!(v="googleads.g.doubleclick.net"==k.host)&&!n.gclid||(n[e[0]]="google",n[e[1]]=v?"display":"cpc"):(n[e[0]]="baidu",n[e[1]]=v?"display":"cpc");t=0;for(y=e[m];t<y;t++)n[e[t]]&&q[u](e[t]+"="+n[e[t]]);e=q[E]("&");l=ua(l.query);n=k="";if(f&&!(-1<h[A](".jinfuzi.com")||"jinfuzi.com"==h)||e){q="daum:q eniro:search_word naver:query pchome:q images.google:q google:q doubleclick:p yahoo:p yahoo:q msn:q bing:q aol:query aol:encquery aol:q lycos:query ask:q altavista:q netscape:query cnn:query about:terms mamma:q alltheweb:q voila:rdata virgilio:qs live:q baidu:wd baidu:w baidu:word baidu:kd cpro.baidu:u alice:qs yandex:text najdi:q mama:query seznam:q search:q wp:szukaj onet:qt szukacz:q yam:k kvasir:q sesam:q ozu:q terra:query mynet:q ekolay:q rambler:query rambler:words sogou:query soso:query youdao:q zhongsou:w haosou.com:q sm.cn:q".split(" ");
t=0;for(y=q[m];t<y;t++)if(v=q[t][x](":"),-1<h[A](v[0]))if(l[v[1]]){k=l[v[1]];-1<v[0][A]("baidu")&&(n=Q(l.ix,10)||"");break}else if(-1<h[A]("google.")){k="(not provided)";break}da=[f,k,e,n]}else da=["","",""]}f=da;h=ba("s");l=!0;e=ja(p,f)[E]("|");if(!f[1]&&!f[2]&&S-g<va||!f[0]&&!f[2]||h==e)h&&(e=h),l=!1;a.rfs=ja(ka,e[x]("|"));ia("s",e,U,Fa);g=l;if(!c)b[u](S,0,1,String(S),0,1);else if(S-b[4]>va||g){b[1]=d[d[m]-1];b[2]++;for(c=d[m]-1;0<=c;c--)if(345600<wa-d[c]){d=d[la](c+1);break}d[u](S);b[3]=d[la](-3)[E](".");
b[5]=b[5]&&(new Date(1E3*b[4])).toDateString()==(new Date).toDateString()?Q(b[5])+1:1}a.vData=a.vData.concat(b);b[4]=S;ia("v",b[E]("|"),U,xa);b=a.vData;a=a.rfs;d=C.cookieEnabled?1:0;c=r.localStorage?1:0;g=b[0];f=B.uid||"";h=L();l=F.title||"";v="ShockwaveFlash";e="";var D;if(C&&C.plugins&&C.plugins.length)(D=C.plugins["Shockwave Flash"])&&D.description&&(e=D.description[x]("Shockwave Flash ")[1]);else{v+="."+v;try{D=new ActiveXObject(v+".7")}catch(z){try{D=new ActiveXObject(v+".6")}catch(G){try{D=
new ActiveXObject(v)}catch(H){}}}D&&(e=D.GetVariable("$version"));e&&(e=e[x](" ")[1][x](","),e=e[0]+"."+e[1]+" r"+e[2])}v=D=r.screen;return{id:"10773",ce:d,lse:c,sid:g,uid:f,cat:1,rf:h,dt:l,fl:e?e:"",sr:D?D.width+"x"+D.height:"",sc:v?v.colorDepth+"-bit":"",la:(C&&(C.language||C.browserLanguage)||"")[I](),pcat:B.pageType||{},item:B.item||{},nuv:b[2]>wa?1:0,auv:3<=b[5][x](".")[m]?1:0,fvt:b[2],lst:b[3],lvt:b[6],vn:b[4],fq:b[7],srf:a[0],srt:a[1],src:a[2],bdix:a[3]||""}}function ta(a){var c=ba("u"),b=
c&&!a?c[x]("|"):[];if(!c||a)b[u](a||pa()+pa(),"jinfuzi.com"),c=b[E]("|");ia("u",c,"jinfuzi.com",xa);return b}function ya(a){F.body?Z("a","click",function(){var c=this.href||"";if(c.match(/^(https|http):\/\//ig)){var b=V(c).host;RegExp(a.vData[1]+"$","i").test(b)||(b=M(this),b.cat=5,b.link=c,R(b))}}):setTimeout(function(){ya(a)},100)}function za(a){F.body?Z("form","submit",function(){for(var c=null,b={submit:1,reset:1,button:1,image:1,file:1,password:1,hidden:1},d=0;d<this.length;d++){var g=this[d],
f=g.nodeName[I](),l=g.type[I]();if(!b[l]&&("checkbox"!=l&&"radio"!=l||g.checked)){if("select"==f){for(var f=g.options,h=[],e,m=0,k=f.length;m<k;m++)e=f[m],e.selected&&h.push(e.text);f=h.join(", ")}else f=N(g.value);!c&&(c=M(a));Aa(a,c,"\u8868\u5355\u8ddf\u8e2a",this.name||this.id||this.className||"none",(g.name||g.id||g.className||"none")+"("+l+"): "+(f||"none"),0)}}}):setTimeout(function(){za(a)},100)}function Ba(a,c){c&&(c.selector?Z(c.selector,c.event||"click",function(){a._trackEvent(c.category,
c.action,c.label,c.value)}):a._trackEvent(c.category,c.action,c.label,c.value))}function Aa(a,c,b,d,g,f){if(""==b||!W(b)||""==d||!W(d))return!1;g=W(g)?g:"";f=isNaN(parseFloat(f))?0:Math.round(100*parseFloat(f))/100;a=c||M(a);a.cat=2;a.ev=[p(b),p(d),p(g),f][E]("|");R(a);return!0}function Ca(){this.autoPV=!0;this.autoForm=this.autoOut=!1;this.vData=[];this.rfs=[]}function ua(a){var c={};if(!a)return c;a=a[x]("&");for(var b=0;b<a[m];b++)if(a[b]){var d=a[b][A]("=");0<d?c[a[b][s](0,d)]=a[b][s](d+1):c[a[b]]=
""}return c}function sa(a){var c=[],b=function(a,d){var m=d instanceof Array,h=typeof d,e;if("object"==h&&null!==d)for(e in d)b(a+"["+(m&&"object"!=typeof d[e]?"":e)+"]",d[e]);else if("function"!=h)c[u](p(a)+"="+(null===d?"":p(d)))},d;for(d in a)b(d,a[d]);return c[E]("&")[w](/%20/g,"+")}function V(a){var c,b,d={protocol:"http",host:"",port:"",path:"",query:"",hash:""};if(!a)return d;b=a[A]("://");0<=b&&(d.protocol=a[s](0,b),a=a[s](b+3));b=a.search("/|\\?|#");c=a[s](0,0<=b?b:a[m])[I]()[x](":");d.host=
c[0];c[1]&&(d.port=c[1]);0<=b&&(a=a[s](b));b=a[A]("#");0<=b&&(d.hash=a[s](b+1),a=a[s](0,b));b=a[A]("?");0<=b&&(d.query=a[s](b+1),a=a[s](0,b));d.path=a;return d}function X(a,c){var b=a.match(RegExp("(\\?|&)"+c+"=([^&]*)(&|$)","i"));return null!=b?ka(b[2]):""}function Ea(){}function W(a){return"string"==typeof a}function H(a){return a[w](Ga,"+")}function ja(a,c){for(var b=[],d=0,g=c[m];d<g;d++)b.push(a(c[d]));return b}function N(a){return null==a?"":a.toString().replace(/^\s+/,"").replace(/\s+$/,"")}
var p=encodeURIComponent,ka=decodeURIComponent,Q=parseInt,T=Math,va=Q("1800"),Fa=Q("15552000"),xa=Q("63072000"),k=function(a){return a.join("")},ca=k(["__tsa_"]),E=k(["join"]),u=k(["push"]),A=k(["indexOf"]),x=k(["split"]),la=k(["slice"]),m=k(["length"]),w=k(["replace"]),I=k(["toLowerCase"]),s=k(["substring"]),O=k(["getTime"]),P=k(["location"]),qa=k(["referrer"]),Y=k(["createElement"]),ea=k(["appendChild"]),Ha=k(["getElementById"]),J=k(["getElementsByClassName"]),ra=k(["//s.va.cn/stats.php"]),
B="object"==typeof r._vaqData?r._vaqData:"object"==typeof r._tsaData?r._tsaData:{};if(-1!=r.name[A]("_checkcode_iframe_"))return r.name+="_vaq_success_",!1;var k=new Date,S=T.round(k[O]()/1E3),wa=(new Date(k.toDateString()))[O]()/1E3,C=r.navigator,U=r[P].hostname,Ga=/%20/g,aa={},da=null;Ca.prototype={init:function(){var a=r[P].href.match(/_vaq=([a-z0-9]{16})/);null!=a&&ta(a[1]);this.autoPV&&this._trackPageview(B.vpv);this.autoOut&&ya(this);this.autoForm&&za(this);B.transaction&&this._trackTrans(B.transaction);
if(B.cart)try{this._trackCart(B.cart)}catch(c){}if(B.event){a=B.event;try{if("[object Array]"==Object.prototype.toString.call(a))for(var b=0,d=a.length;b<d;b++)Ba(this,a[b]);else Ba(this,a)}catch(m){}}if(B.search){d=B.search;try{this._trackSiteSearch(d.keyword,d.category,d.count)}catch(f){}}},_liveEvent:function(){Z.apply(r,arguments)},_setDomainName:function(a){U=a},_setAutoPageview:function(a){this.autoPV=!!a},_setAutoOutbound:function(a){this.autoOut=!!a},_setAutoTrackForm:function(a){this.autoForm=
!!a},_trackPageview:function(a){var c=M(this);a&&(c.p="/"==a.substr(0,1)?a:"/"+a);R(c)},_trackEvent:function(a,c,b,d){return Aa(this,null,a,c,b,d)},_trackSiteSearch:function(a,c,b){if(""==a||!W(a))return!1;c=W(c)?c:"";if(!1===b)b="";else{var d=Q(b,10);b=("number"==typeof d||void 0!=Number&&d instanceof Number)&&Math.round(d)==d&&!isNaN(d)&&Infinity!=d?Q(b,10):0}d=M(this);d.cat=6;d.sst=[p(a),p(c),b][E]("|");R(d);return!0},_trackChat:function(a,c){var b=ha(a);this._setAutoPageview(!1);var d,g=this;
try{d=parent.document}catch(f){d=F}d||(d=F);var l={};l["127144847"]=X(L(),"p")||L();l["265026962"]=X(d[P].search,"enterurl")||L(d);l["14340467"]=X(d[P].search,"referer")||L(d);l["152445476"]=X(d[P].search,"loc")||X(F[P].search,"loc")||L(d);if(l[b]!==Da){var h=d[Y]("form");h.method="post";h.target="vaq_iframe";h.style.display="none";d.body[ea](h);var e;try{e=d[Y]('<iframe name="'+h.target+'"></iframe>')}catch(k){e=d[Y]("iframe"),e.name=h.target}e.id=h.target;e.style.display="none";d.body[ea](e);var q=
d[Y]("input");q.name="service";h[ea](q);var s=d[Y]("input");s.name="client";h[ea](s);var t=[],y=[],v=0,B=function(){this[J]=function(){var a="*";1<arguments[m]&&(a=arguments[1]);for(var a=(2<arguments[m]?arguments[2]:this).getElementsByTagName(a),b=[],c,d=" "+arguments[0]+" ",e=0;e<a[m];e++)if(c=" "+a[e].className+" ",-1!=c[A](d))b[u](a[e]);return b}},D={127144847:function(){t=[];y=[];var a=d[Ha]("chatwordsFrame");if(a){a=a.contentDocument||a.contentWindow.document;a[J]||B.apply(a);for(var b=a[J]("operatornamefont"),
e=a[J]("operatorfont"),f=0;f<b[m];f++)if("1"!=b[f].getAttribute("chk")){b[f].setAttribute("chk","1");var g=ja(p,b[f].innerHTML[x]("&nbsp;"));if("%5B%E7%B3%BB%E7%BB%9F%E6%8F%90%E7%A4%BA%5D"!=g[0])t[u]([N(g[0]),p(G()),p(c?e[f].innerHTML:"***")][E](","))}b=a[J]("clientnamefont");a=a[J]("clientfont");for(f=0;f<b[m];f++)"1"!=b[f].getAttribute("chk")&&(b[f].setAttribute("chk","1"),y[u]([p(G()),p(c?a[f].innerHTML:"***")][E](",")))}},265026962:function(){var a="",b="",e="";t=[];y=[];for(var f=d.getElementById("padding")?
d.getElementById("padding").childNodes:[],g=0;g<f[m];g++){if("operator"==f[g].className||"visitor"==f[g].className)a=p(N(f[g].childNodes[0].nodeValue))[w]("%E8%AF%B4%3A",""),e=c?p(f[g].childNodes[2].innerHTML):"***";else if(""==a)continue;else e=c?p(f[g].childNodes[0].innerHTML):"***";if("1"!=f[g].getAttribute("chk"))if(f[g].setAttribute("chk","1"),b=p(G()),"%E6%82%A8"==a)y[u]([b,e]);else t[u]([a,b,e])}},14340467:function(){d[J]||B.apply(d);t=[];y=[];var a=d[J]("talk-item"),b,e,f,g,h;if(a&&a.length){var l=
/message_content/,k=/msg-worker/,q=/msg-visitor/,r,n,s;for(b=v;b<a[m];b++){h=a[b];e=h.innerHTML[x]("&nbsp;");f=p(N(e[0]));g=p(G());e="";n=h.childNodes;for(r=n[m];s=n[--r];)if(l.test(s.className)){n=s.childNodes;if(r=n[m])for(var w;w=n[--r];)if(3==w.nodeType){e+=s.innerHTML;break}else e+=w.innerHTML;break}if(e)if(e=c?encodeURIComponent(e):"***",h=h.className,k.test(h))t[u]([f,g,e]);else if(q.test(h))y[u]([g,e])}}else for(a=d[J]("send-msg-name"),b=v;b<a[m];b++){e=a[b].innerHTML[x]("&nbsp;");f=p(N(e[0]));
g=p(G());e="";for(h=a[b].nextSibling;h&&"p"==h.nodeName[I]();)e+=h.innerHTML,h=h.nextSibling;if(e)if(e=c?p(e):"***","send-msg-content"==a[b].nextSibling.className)y[u]([g,e]);else t[u]([f,g,e])}v=a[m]},152445476:function(){var a,b=function(){var b=$||{};if(!b.ajaxSetting||!b.ajaxSetting.complete)return!1;var e=b.ajaxSetting.complete,f=function(a,b){var f;if(a&&(f=(new Function("","return "+a.responseText))())&&"success"==f.status){t=[];y=[];for(var g=(this&&this.url?-1<this.url[A]("?")?this.url.substr(this.url[A]("?")+
1):this.url:"")[x]("&"),h={},l=0;l<g[m];l++){var k=g[l][x]("=");0!=k[0][A]("_")&&(h[k[0]]=ka(k[1]?k[1][w](/\+/g," "):""))}var n;if("pump"==h.cmd){if(f.result&&f.result[m]){f=f.result;try{n=H(p(conf.realName))}catch(r){n=""}g=["<ACCEPT>","<GETFOCUS>","<OPINION>"];h=0;for(l=f[m];h<l;h++){var k=f[h].msg,q=1;if(!k)break;for(var s=0,v=g[m];s<v;s++)if(0<=k[A](g[s])){q=0;break}q&&t[u]([n,H(p(G())),c?H(p(d(k))):"***"])}}}else"postMessage"==h.cmd&&(h.msg&&y[u]([H(p(G())),c?H(p(d(h.msg))):"***"]),"FILE"==h.type&&
y[u]([H(p(G())),c?H(p("\u53d1\u9001\u4e86\u6587\u4ef6")):"***"]),"SCREENSHOTS"==h.type&&y[u]([H(p(G())),c?H(p("\u53d1\u9001\u4e86\u622a\u5c4f")):"***"]));var z;try{z=conf.UId||conf.VId}catch(B){z=0}C(z)}return e&&e(a,b)};f._tsa_w=1;b.ajaxSetting.complete=e._tsa_w?e:f;clearInterval(a);return!0},d=function(a){return a?(""+a)[w](/^<FILE>.*?$/,"\u53d1\u9001\u4e86\u6587\u4ef6")[w](/^<SCREENSHOTS>.*?$/,"\u53d1\u9001\u4e86\u622a\u5c4f")[w](/^<TRANSCHAT>.*?$/,"\u53d1\u751f\u4e86\u5bf9\u8bdd\u8f6c\u79fb")[w](/^<TRANS>.*?$/,
"\u5bf9\u8bdd\u8f6c\u79fb\u6210\u529f")[w](/\[!\d*\]/ig,"[\u8868\u60c5]")[w](/<div.*?<\/div>/ig,"[\u8868\u60c5]")[w](/^<ROBOTCHAT>begin.*?$/,"\u8be5\u7528\u6237\u5df2\u7ecf\u6258\u7ba1\u7ed9\u5e94\u7b54\u7cfb\u7edf")[w](/^<ROBOTCHAT>end.*?$/,"\u53d6\u6d88\u8be5\u7528\u6237\u6258\u7ba1"):a};b()||(a=setInterval(b,100))}},z=1,C=function(c){"152445476"!==b&&D[b]();if(t[m]||y[m]||z){q.value=t[E]("|");s.value=y[E]("|");var d=M(g);d.cat=3;d.chat=a;c&&(d.chatsid=c);d.chatclk=z;d.rf=l[b];d.ts=T.round((new Date)[O]()/
1E3);h.action=ra+"?"+sa(d);h.submit();z=0}};if("152445476"==b)D[b]();else{C();try{top.window.setInterval(C,2E3)}catch(K){setInterval(C,2E3)}ga(d,"mouseup",C);ga(d,"keyup",function(a){a=a||r.event;(13==(a.keyCode||a.witch)||a.ctrlKey||a.altKey)&&C()})}}},trackChat:function(a,c){this._trackChat(a,c)},_trackTrans:function(a){if(!a)return!1;var c=M(this);c.cat=4;c.trans=a;R(c);return!0},_trackCart:function(a){if(!a)return!1;var c=M(this);c.cat=7;c.cart=a;R(c);return!0},_link:function(a,c){var b=V(a),
d=c?"hash":"query";b[d]+=(b[d]?"&":"")+"_vaq="+ba("u")[x]("|")[0];return b.protocol+"://"+b.host+(b.port?":"+b.port:"")+b.path+(b.query?"?"+b.query:"")+(b.hash?"#"+b.hash:"")}};var fa=new Ca,k=["_setAutoPageview","_setDomainName"],ma=[],z=[],K=r._vaq;K?z=K:r._vaq=z;var K=[],q=r._tsa;q?K=q:r._tsa=K;for(q=0;q<K[m];q++)z.push(K[q]);z[u]=function(a){return fa[a[0]]&&fa[a[0]].apply(fa,a[la](1))};K[u]=z[u];for(q=0;q<z[m];q++)if(-1!=(","+k[E](",")+",")[A](z[q][0]))z[u](z[q]);else ma[u](z[q]);for(q=0;q<ma[m];q++)z[u](ma[q]);
fa.init()})(window,document);
